/**
 */
package sQL2AMN.amn.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import sQL2AMN.amn.util.AmnAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class AmnItemProviderAdapterFactory extends AmnAdapterFactory
		implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public AmnItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link sQL2AMN.amn.AMNMachine} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AMNMachineItemProvider amnMachineItemProvider;

	/**
	 * This creates an adapter for a {@link sQL2AMN.amn.AMNMachine}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAMNMachineAdapter() {
		if (amnMachineItemProvider == null) {
			amnMachineItemProvider = new AMNMachineItemProvider(this);
		}

		return amnMachineItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link sQL2AMN.amn.Variable} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VariableItemProvider variableItemProvider;

	/**
	 * This creates an adapter for a {@link sQL2AMN.amn.Variable}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVariableAdapter() {
		if (variableItemProvider == null) {
			variableItemProvider = new VariableItemProvider(this);
		}

		return variableItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link sQL2AMN.amn.Operation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OperationItemProvider operationItemProvider;

	/**
	 * This creates an adapter for a {@link sQL2AMN.amn.Operation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOperationAdapter() {
		if (operationItemProvider == null) {
			operationItemProvider = new OperationItemProvider(this);
		}

		return operationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link sQL2AMN.amn.StringLiteral} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StringLiteralItemProvider stringLiteralItemProvider;

	/**
	 * This creates an adapter for a {@link sQL2AMN.amn.StringLiteral}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStringLiteralAdapter() {
		if (stringLiteralItemProvider == null) {
			stringLiteralItemProvider = new StringLiteralItemProvider(this);
		}

		return stringLiteralItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link sQL2AMN.amn.VarRef} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VarRefItemProvider varRefItemProvider;

	/**
	 * This creates an adapter for a {@link sQL2AMN.amn.VarRef}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVarRefAdapter() {
		if (varRefItemProvider == null) {
			varRefItemProvider = new VarRefItemProvider(this);
		}

		return varRefItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link sQL2AMN.amn.SetMembership} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SetMembershipItemProvider setMembershipItemProvider;

	/**
	 * This creates an adapter for a {@link sQL2AMN.amn.SetMembership}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSetMembershipAdapter() {
		if (setMembershipItemProvider == null) {
			setMembershipItemProvider = new SetMembershipItemProvider(this);
		}

		return setMembershipItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link sQL2AMN.amn.Conjuction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConjuctionItemProvider conjuctionItemProvider;

	/**
	 * This creates an adapter for a {@link sQL2AMN.amn.Conjuction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConjuctionAdapter() {
		if (conjuctionItemProvider == null) {
			conjuctionItemProvider = new ConjuctionItemProvider(this);
		}

		return conjuctionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link sQL2AMN.amn.InvariantPredicate} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InvariantPredicateItemProvider invariantPredicateItemProvider;

	/**
	 * This creates an adapter for a {@link sQL2AMN.amn.InvariantPredicate}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInvariantPredicateAdapter() {
		if (invariantPredicateItemProvider == null) {
			invariantPredicateItemProvider = new InvariantPredicateItemProvider(this);
		}

		return invariantPredicateItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link sQL2AMN.amn.SetDefinition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SetDefinitionItemProvider setDefinitionItemProvider;

	/**
	 * This creates an adapter for a {@link sQL2AMN.amn.SetDefinition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSetDefinitionAdapter() {
		if (setDefinitionItemProvider == null) {
			setDefinitionItemProvider = new SetDefinitionItemProvider(this);
		}

		return setDefinitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link sQL2AMN.amn.AssignSubtitution} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AssignSubtitutionItemProvider assignSubtitutionItemProvider;

	/**
	 * This creates an adapter for a {@link sQL2AMN.amn.AssignSubtitution}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAssignSubtitutionAdapter() {
		if (assignSubtitutionItemProvider == null) {
			assignSubtitutionItemProvider = new AssignSubtitutionItemProvider(this);
		}

		return assignSubtitutionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link sQL2AMN.amn.SkipSubtitution} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SkipSubtitutionItemProvider skipSubtitutionItemProvider;

	/**
	 * This creates an adapter for a {@link sQL2AMN.amn.SkipSubtitution}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSkipSubtitutionAdapter() {
		if (skipSubtitutionItemProvider == null) {
			skipSubtitutionItemProvider = new SkipSubtitutionItemProvider(this);
		}

		return skipSubtitutionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link sQL2AMN.amn.AnySubtitution} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AnySubtitutionItemProvider anySubtitutionItemProvider;

	/**
	 * This creates an adapter for a {@link sQL2AMN.amn.AnySubtitution}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAnySubtitutionAdapter() {
		if (anySubtitutionItemProvider == null) {
			anySubtitutionItemProvider = new AnySubtitutionItemProvider(this);
		}

		return anySubtitutionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link sQL2AMN.amn.SelectSubtitution} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SelectSubtitutionItemProvider selectSubtitutionItemProvider;

	/**
	 * This creates an adapter for a {@link sQL2AMN.amn.SelectSubtitution}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSelectSubtitutionAdapter() {
		if (selectSubtitutionItemProvider == null) {
			selectSubtitutionItemProvider = new SelectSubtitutionItemProvider(this);
		}

		return selectSubtitutionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link sQL2AMN.amn.IfSubtitution} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IfSubtitutionItemProvider ifSubtitutionItemProvider;

	/**
	 * This creates an adapter for a {@link sQL2AMN.amn.IfSubtitution}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIfSubtitutionAdapter() {
		if (ifSubtitutionItemProvider == null) {
			ifSubtitutionItemProvider = new IfSubtitutionItemProvider(this);
		}

		return ifSubtitutionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link sQL2AMN.amn.SequentialSubtitution} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SequentialSubtitutionItemProvider sequentialSubtitutionItemProvider;

	/**
	 * This creates an adapter for a {@link sQL2AMN.amn.SequentialSubtitution}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSequentialSubtitutionAdapter() {
		if (sequentialSubtitutionItemProvider == null) {
			sequentialSubtitutionItemProvider = new SequentialSubtitutionItemProvider(this);
		}

		return sequentialSubtitutionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link sQL2AMN.amn.PreSubtitution} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PreSubtitutionItemProvider preSubtitutionItemProvider;

	/**
	 * This creates an adapter for a {@link sQL2AMN.amn.PreSubtitution}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPreSubtitutionAdapter() {
		if (preSubtitutionItemProvider == null) {
			preSubtitutionItemProvider = new PreSubtitutionItemProvider(this);
		}

		return preSubtitutionItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>) type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void dispose() {
		if (amnMachineItemProvider != null)
			amnMachineItemProvider.dispose();
		if (variableItemProvider != null)
			variableItemProvider.dispose();
		if (operationItemProvider != null)
			operationItemProvider.dispose();
		if (stringLiteralItemProvider != null)
			stringLiteralItemProvider.dispose();
		if (varRefItemProvider != null)
			varRefItemProvider.dispose();
		if (setMembershipItemProvider != null)
			setMembershipItemProvider.dispose();
		if (conjuctionItemProvider != null)
			conjuctionItemProvider.dispose();
		if (invariantPredicateItemProvider != null)
			invariantPredicateItemProvider.dispose();
		if (setDefinitionItemProvider != null)
			setDefinitionItemProvider.dispose();
		if (assignSubtitutionItemProvider != null)
			assignSubtitutionItemProvider.dispose();
		if (skipSubtitutionItemProvider != null)
			skipSubtitutionItemProvider.dispose();
		if (anySubtitutionItemProvider != null)
			anySubtitutionItemProvider.dispose();
		if (selectSubtitutionItemProvider != null)
			selectSubtitutionItemProvider.dispose();
		if (ifSubtitutionItemProvider != null)
			ifSubtitutionItemProvider.dispose();
		if (sequentialSubtitutionItemProvider != null)
			sequentialSubtitutionItemProvider.dispose();
		if (preSubtitutionItemProvider != null)
			preSubtitutionItemProvider.dispose();
	}

}
