CREATE TABLE registry.land_type (
    land_type_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    group_id BIGINT,
    name VARCHAR,
    soil VARCHAR,
    CONSTRAINT land_type_pk PRIMARY KEY (land_type_id)
);

CREATE TABLE registry.tmp_land (
    region VARCHAR,
    type_name VARCHAR,
    soil VARCHAR
);

CREATE OR REPLACE FUNCTION registry.integrate_land()
RETURNS VOID AS $$
DECLARE
    r_land RECORD;
    v_type_id BIGINT;
BEGIN
    FOR r_land IN (SELECT * FROM registry.tmp_land) LOOP

        SELECT land_type_id INTO v_type_id
        FROM registry.land_type
        WHERE name = r_land.type_name;

        IF v_type_id IS NULL THEN
            INSERT INTO registry.land_type
                (name, soil)
            VALUES
                (r_land.type_name, r_land.soil);
        END IF;

    END LOOP;
END;
$$ LANGUAGE plpgsql;