#

pluginName = SQL2AMN Edit Support
providerName = www.example.org

_UI_CreateChild_text = {0}
_UI_CreateChild_text2 = {1} {0}
_UI_CreateChild_text3 = {1}
_UI_CreateChild_tooltip = Create New {0} Under {1} Feature
_UI_CreateChild_description = Create a new child of type {0} for the {1} feature of the selected {2}.
_UI_CreateSibling_description = Create a new sibling of type {0} for the selected {2}, under the {1} feature of their parent.

_UI_PropertyDescriptor_description = The {0} of the {1}

_UI_SQLProgram_type = SQL Program
_UI_Procedure_type = Procedure
_UI_Statement_type = Statement
_UI_CreateTableStatement_type = Create Table Statement
_UI_InsertStatement_type = Insert Statement
_UI_SelectIntoStatement_type = Select Into Statement
_UI_IfStatement_type = If Statement
_UI_ForLoopStatement_type = For Loop Statement
_UI_VariableDeclaration_type = Variable Declaration
_UI_Expression_type = Expression
_UI_LiteralExpression_type = Literal Expression
_UI_VariableExpression_type = Variable Expression
_UI_FieldAcessExpression_type = Field Acess Expression
_UI_AMNMachine_type = AMN Machine
_UI_Variable_type = Variable
_UI_Operation_type = Operation
_UI_Substitution_type = Substitution
_UI_StringLiteral_type = String Literal
_UI_VarRef_type = Var Ref
_UI_SetMembership_type = Set Membership
_UI_Conjuction_type = Conjuction
_UI_InvariantPredicate_type = Invariant Predicate
_UI_SetDefinition_type = Set Definition
_UI_Expression_type = Expression
_UI_AssignSubtitution_type = Assign Subtitution
_UI_SkipSubtitution_type = Skip Subtitution
_UI_AnySubtitution_type = Any Subtitution
_UI_SelectSubtitution_type = Select Subtitution
_UI_IfSubtitution_type = If Subtitution
_UI_SequentialSubtitution_type = Sequential Subtitution
_UI_PreSubtitution_type = Pre Subtitution
_UI_Unknown_type = Object

_UI_Unknown_datatype= Value

_UI_SQLProgram_procedures_feature = Procedures
_UI_Procedure_name_feature = Name
_UI_Procedure_body_feature = Body
_UI_Procedure_declarations_feature = Declarations
_UI_CreateTableStatement_tableName_feature = Table Name
_UI_InsertStatement_tableName_feature = Table Name
_UI_InsertStatement_columns_feature = Columns
_UI_SelectIntoStatement_targetVar_feature = Target Var
_UI_SelectIntoStatement_sourceColumn_feature = Source Column
_UI_SelectIntoStatement_fromTable_feature = From Table
_UI_IfStatement_thenBranch_feature = Then Branch
_UI_IfStatement_elseBranch_feature = Else Branch
_UI_IfStatement_condition_feature = Condition
_UI_ForLoopStatement_loopVar_feature = Loop Var
_UI_ForLoopStatement_fromTable_feature = From Table
_UI_ForLoopStatement_body_feature = Body
_UI_VariableDeclaration_name_feature = Name
_UI_VariableDeclaration_typeName_feature = Type Name
_UI_LiteralExpression_value_feature = Value
_UI_VariableExpression_name_feature = Name
_UI_FieldAcessExpression_objectName_feature = Object Name
_UI_FieldAcessExpression_fieldName_feature = Field Name
_UI_AMNMachine_name_feature = Name
_UI_AMNMachine_variables_feature = Variables
_UI_AMNMachine_operations_feature = Operations
_UI_AMNMachine_invariants_feature = Invariants
_UI_AMNMachine_sets_feature = Sets
_UI_Variable_name_feature = Name
_UI_Variable_typeName_feature = Type Name
_UI_Operation_name_feature = Name
_UI_Operation_body_feature = Body
_UI_StringLiteral_value_feature = Value
_UI_VarRef_name_feature = Name
_UI_SetMembership_left_feature = Left
_UI_SetMembership_right_feature = Right
_UI_Conjuction_left_feature = Left
_UI_Conjuction_right_feature = Right
_UI_InvariantPredicate_text_feature = Text
_UI_SetDefinition_name_feature = Name
_UI_AssignSubtitution_variable_feature = Variable
_UI_AssignSubtitution_value_feature = Value
_UI_AnySubtitution_boundVar_feature = Bound Var
_UI_AnySubtitution_condition_feature = Condition
_UI_AnySubtitution_thenBody_feature = Then Body
_UI_SelectSubtitution_condition_feature = Condition
_UI_SelectSubtitution_thenBody_feature = Then Body
_UI_IfSubtitution_condition_feature = Condition
_UI_IfSubtitution_thenBody_feature = Then Body
_UI_IfSubtitution_elseBody_feature = Else Body
_UI_SequentialSubtitution_first_feature = First
_UI_SequentialSubtitution_second_feature = Second
_UI_PreSubtitution_guard_feature = Guard
_UI_PreSubtitution_body_feature = Body
_UI_Unknown_feature = Unspecified

